<?php
return array(
	'DATABASE_HOST'		=> 'mobstar-production.cyz3qf3vz9qw.eu-west-1.rds.amazonaws.com',
	'DATABASE_USER' => 'root',
    'DATABASE_PASSWORD'	=> 'd0wnund3r',
    'DATABASE_DATABASE' => 'dotIdol',
    'PATH'				=> '/var/www/api/',
    'TMP'				=> '/tmp/',
    'URL'				=> 'api.mobstar.com',
    'URL_ADMIN'				=> 'admin.mobstar.com',
	'DEBUG'				=> true,
    'bucket' => 'mobstar-1',
    'DUMP_REQUESTS' => false,
    'BIN_FFMPEG' => '/usr/bin/ffmpeg',
    'BIN_FFPROBE' => '/usr/bin/ffprobe',
    'MAX_MEDIA_DURATION_FOR_HOME_FEED' => 30,
    'DISABLE_SNS' => false,
    'DISABLE_YOUTUBE_UPLOAD' => false,
    'KEEP_UPLOADED_ENTRY_FILES' => false,
);
